spring.application.name=ai
spring.ai.openai.api-key=sk-xxx
spring.ai.openai.api-url=http://10.192.23.203:8001/v1/chat/completions
#spring.ai.vectorstore.chroma.url=http://10.192.23.250:8000

spring.datasource.url=jdbc:sqlserver://10.192.1.5:1433;databaseName=aidb_test;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Pkuih@2023
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

ragflow.base-url=http://10.192.23.250:8888
ragflow.api-url=http://10.192.23.250:8888/api/v1
ragflow.api-key=ragflow-E4ODk1OTNhZmU0MDExZWZhYWJjMDI0Mm

logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration

#spring.datasource.tomcat.jmx-enabled=false